### ISSUE TITLE
failed to start on ubuntu...

### ISSUE THREAD

**Issue by Zibri** [dynsdjs/dynsdjs#2]
I did:
```
# git clone https://github.com/dynsdjs/dynsdjs
# cd dynsdjs/
# npm install
# npm link
# dynsd
```
module.js:549
    throw err;
    ^

Error: Cannot find module '../dist/Dynsd'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/dynsdjs/bin/cli.js:3:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

**Comment by Zibri** [comment]
npm install also threw these warnings:

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.4
npm WARN enoent ENOENT: no such file or directory, open '/root/dynsdjs/node_modules/acorn-dynamic-import/package.json'
npm WARN webpack-source-map-support@2.0.1 requires a peer of webpack@^1.13.3 but none was installed.

**Comment by julianxhokaxhiu** [comment]
Sorry for the super late reply on this issue, but feel free to try the latest master. A lot of dependencies just deprecated in time and the project fall on its own ashes.

**Comment by julianxhokaxhiu** [comment]
I've personally tested the entire solution and it works fine by now. Let me know in case if you still face any issue in the future.
